name: Update GitHub Stats Cards

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Top Languages Card
        uses: stats-organization/github-readme-stats-action@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          card: top-langs
          username: romulo-rp29
          options: 'layout=compact&theme=dracula'
          path: ./top-langs.svg

      - name: Push SVG to Repository
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update stats card"
          file_pattern: 'top-langs.svg'
